### ISSUE TITLE
Bounding box geeft strings ipv floats 

### ISSUE THREAD

**Issue by cedrikv** [OnroerendErfgoed/crabpy_pyramid#152]
bvb 
![image](https://user-images.githubusercontent.com/1849458/141949383-41327090-9adf-428f-b262-61bd2eb03f86.png)
https://test-geo.onroerenderfgoed.be/crab/straten/59903

De doc zegt dit:
![image](https://user-images.githubusercontent.com/1849458/141949477-09634fca-9eec-4c03-b862-06dabd77521a.png)

**Comment by vancamti** [comment]
Issue moved to [OnroerendErfgoed/crabpy #168](https://github.com/OnroerendErfgoed/crabpy/issues/168) via [**ZenHub**](https://www.zenhub.com/)
