### ISSUE TITLE
Maximum op aantal resultaten in percelen

### ISSUE THREAD

**Issue by claeyswo** [OnroerendErfgoed/crabpy_pyramid#16]
https://github.com/OnroerendErfgoed/crabpy_pyramid/blob/master/crabpy_pyramid/utils.py#L10

Blijkbaar is dit enkel als er geen Range headers worden meegestuurd.

**Comment by koenedaele** [comment]
Currently, there's a maximum on the number of items that can be loaded. But only if the client didn't send any range headers. If the client did send a range header, eg. `items=0-9999`, we currently ignore the max number of items.

So, if a client asks for more than max items, we should only send max items. And if a client didn't specify a number of items, we only send the max number of items.

**Comment by koenedaele** [comment]
@BartSaelen Can you check this and merge if ready?

**Comment by koenedaele** [comment]
Checked and merged.
