### ISSUE TITLE
Nice to haves

### ISSUE THREAD

**Issue by claeyswo** [OnroerendErfgoed/crabpy_pyramid#184]
https://dev-geo.onroerenderfgoed.be/adressenregister/percelen/23070E0309-00X000

Daar eventueel ook de notatie met / toelaten 23070E0309/00X000

https://github.com/OnroerendErfgoed/crabpy_pyramid/blob/803c72fd142c0e0a31bd85039fca36d70828e418/crabpy_pyramid/routes/adressenregister.py#L102

Ik vraaag mij af of het daar ook niet mogelijk is om niscode toe te laten: gemeenten/{niscode}/postinfo door in 2 tijden te gaan, eerst via niscode naam ophalen

**Comment by vancamti** [comment]
> https://dev-geo.onroerenderfgoed.be/adressenregister/percelen/23070E0309-00X000
> 
> Daar eventueel ook de notatie met / toelaten 23070E0309/00X000
> 
geen idee of dat mogelijk is want / is deel van de url. Waarschijnlijk is wel een route mogelijk met iets als https://dev-geo.onroerenderfgoed.be/adressenregister/percelen/{part1}/{part2} maar ech proper vind ik da ni

**Comment by vancamti** [comment]
> Ik vraaag mij af of het daar ook niet mogelijk is om niscode toe te laten: gemeenten/{niscode}/postinfo door in 2 tijden te gaan, eerst via niscode naam ophalen

lijkt me zeker mogelijk
