### ISSUE TITLE
Add a list of countries

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/crabpy_pyramid#30]
Add rest endpoints, exposing stuff from the pycountry dataset:

 * `/crab/landen`: A list of countries, containing the ISO 3166 country code and a label in Dutch (if available).
 * `/crab/landen/BE`: More information on a certain country.

Example JSON responses:

List 
```js
[
 {
  'id': BE,
  'naam': "België"
 }
]
```

Detail
```js
{
 'id': 'BE',
 'alpha2': 'BE',
 'alpha3': 'BEL',
 'naam': "België",
}
```

**Comment by TalissaJoly** [comment]
Is it usefull to return both id and alpha2?

**Comment by koenedaele** [comment]
Yes, just to make it clear that there's one that we use as id, but that there are actually multiple valid id's.
