### ISSUE TITLE
Blacklist uitlezen voor conditional tween

### ISSUE THREAD

**Issue by claeyswo** [OnroerendErfgoed/crabpy_pyramid#41]
https://github.com/OnroerendErfgoed/premieaanvragen/issues/117

https://github.com/OnroerendErfgoed/crabpy_pyramid/blob/master/crabpy_pyramid/__init__.py#L171

Settings uitlezen en indien blacklist bestaat op basis daarvan filteren of er al dan niet een etag wordt aangemaakt.

**Comment by BartSaelen** [comment]
Ik zou de ETag ook weglaten als de body van de response leeg is

**Comment by BartSaelen** [comment]
sample config:

```
not.cachable.list =
    /aanmelden
    /zever
```
