### ISSUE TITLE
Caching tween volledig herwerken

### ISSUE THREAD

**Issue by claeyswo** [OnroerendErfgoed/crabpy_pyramid#97]
https://github.com/OnroerendErfgoed/dossierdata/issues/232

Samengevat:

- We implementeren optie 1. Standaard staat de tween aan, maar je kunt ze makkelijk afzetten. (Dit om backwards compatible te zijn. We kunnen er ook een opt-in van maken, maar dan moet dat SemVer gewijs duidelijk zijn)
- Indien de tween actief is, dan hanteert deze een lijst van routes die cacheable zijn. Zorg dat het eenvoudig is om de lijst van routes uit te breiden in een bepaalde toepassing.
- HTTP responses >= 400 krijgen geen ETag

Ik zou op PUT en POST die ETag nog wel meesturen. Ik zie er mss ook niet direct het nut van in maar ik durf niet te garanderen dat we daar al niet ergens van uitgaan.

**Comment by Wim-De-Clercq** [comment]
Voor die lijst van routes die cachable zijn:
De huide niet-cachable lijst is via de setting `not.cachable.list`. Moet deze nieuwe setting dan `cachable.list` zijn?

Ik vind het ergens wel een beetje een dubieuze naam omdat we eigenlijk geen caching doen. We laten de caching over aan de caller en helpen daarbij door Etags te sturen.

**Comment by Wim-De-Clercq** [comment]
Ik denk wel dat we beter route names ipv route paths gebruiken voor de not.cachable.list en cachable.list.

Urls die variabel zijn - dus alles met een ID in zoals `/dossiers/3` - kunnen momenteel niet geconfigureerd worden om wel of niet cachable te zijn omdat je het volledige path moet matchen.

Ik ben wel niet zeker hoe het backwards compatibel te houden... met volledig nieuwe settings namen? Dus `non.cachable.list` blijft path only. En dan nieuwe setting namen uitvinden voor route names?

**Comment by claeyswo** [comment]
> Ik ben wel niet zeker hoe het backwards compatibel te houden... met volledig nieuwe settings namen? Dus non.cachable.list blijft path only. En dan nieuwe setting namen uitvinden voor route names?

Ik weet niet of het nodig is om bw compatible te zijn. Ik zou enkel nog een generate_etag_for.list of zoiets behouden met dan inderdaad route names.

**Comment by koenedaele** [comment]
Heeft het eigenlijk nog zin dat dit in CRABpy_pyramid zit? Zou dit beter apart zitten? Dit lijkt me functionaliteit die nuttig is in elk project?

**Comment by claeyswo** [comment]
De manier van etags genereren binnen onze andere projecten is anders dan hier. Daar gebruiken we een uuid die tegelijk ook dienst doet als version column voor sqlaclcehmy.

**Comment by claeyswo** [comment]
Maar we moeten algemeen wel eens bekijken wat we juist met die etag's willen bereiken. Voor alle andere toepassingen was dit eerder het vermijden van concurrent updates. Ik denk zelf niet dat bvb. dossierdata 304's terugstuurt als de resource niet gewijzigd is.

**Comment by Wim-De-Clercq** [comment]
Het enige dat deze van de tween bereiken is minder te hoeven downloaden bij de clients die deze crabpy urls requesten.
